### ISSUE TITLE
Move open issues from old website here

### ISSUE THREAD

**Issue by simonpoole** [okfn/opendatacommons.org#4]
There is at least one important issue that is in danger of getting lost due to the change in website: https://github.com/okfn/opendatacommons/issues/3  that should be moved here, naturally it would be even better if the issue was actually addressed.

**Comment by chris48s** [comment]
Hello. Having reviewed the issues on there:

- The website is up
- We've moved it off wordpress
- The "plain language summary" link on https://opendatacommons.org/licenses/odbl/1-0/ works

So I think https://github.com/okfn/opendatacommons/issues/3 is the only one that is still "current". Maybe also https://github.com/okfn/opendatacommons/issues/5 ?

For issues that are about changing the legal text of the licence or the governance of how it is updated (rather than the website that hosts them), I think https://discuss.okfn.org/c/projects/opendefinition/66 is probably the right place for those discussions now. If you'd like to advance discussion of https://github.com/okfn/opendatacommons/issues/3 then a thread at https://discuss.okfn.org/c/projects/opendefinition/66 referencing that original issue is probably more likely to engage the right people in the conversation. There may also already be a relevant thread there. We can keep the issue tracker here for issues about the website itself.

Thanks

/cc @StephenAbbott

**Comment by simonpoole** [comment]
The issue at hand was already discussed in https://discuss.okfn.org/t/is-odc-by-a-sharealike-licence/6417/14 It isn't the patch itself that is in question, it is just the issue of jacking up (a suitable) minor version number when applying the patch indicating that this was a big oops.

-not- holding my breath on this though.
